name: macOS N111
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/base.yml
    with:
      compiler: "ocaml-variants.4.11.1+BER"
      os: "macos-latest"
